/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Authentication response schema.
 *
 * @param accessToken 
 * @param refreshToken 
 * @param user 
 * @param responseType 
 */
@Serializable

data class AuthResponse (

    @SerialName(value = "access_token") val accessToken: kotlin.String,

    @SerialName(value = "refresh_token") val refreshToken: kotlin.String,

    @SerialName(value = "user") val user: UserResponse,

    @SerialName(value = "response_type") val responseType: AuthResponse.ResponseType? = ResponseType.already_linked

)   {

    /**
     * 
     *
     * Values: already_linked
     */
    @Serializable
    enum class ResponseType(val value: kotlin.String) {
        @SerialName(value = "already_linked") already_linked("already_linked");
    }

}

