/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param `data` 
 * @param total 
 */
@Serializable

data class AvailabilitySearchResponse (

    @SerialName(value = "data") val `data`: kotlin.collections.List<ProviderWithSlotResponse>,

    @SerialName(value = "total") val total: kotlin.Int

)   {

}

