/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param startTime Start of search window
 * @param endTime End of search window
 * @param durationMinutes Required duration in minutes
 * @param serviceIds Services to book
 * @param sortBy Sort by rating or price
 */
@Serializable

data class AvailabilitySearchRequest (

    /* Start of search window */
    @SerialName(value = "start_time") val startTime: kotlinx.datetime.Instant,

    /* End of search window */
    @SerialName(value = "end_time") val endTime: kotlinx.datetime.Instant,

    /* Required duration in minutes */
    @SerialName(value = "duration_minutes") val durationMinutes: kotlin.Int,

    /* Services to book */
    @SerialName(value = "service_ids") val serviceIds: kotlin.collections.List<kotlin.String>,

    /* Sort by rating or price */
    @SerialName(value = "sort_by") val sortBy: kotlin.String? = "rating"

)   {

}

