/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param bookingId 
 * @param serviceId 
 * @param serviceName 
 * @param price 
 * @param durationMinutes 
 * @param createdAt 
 * @param currency 
 */
@Serializable

data class BookingItemResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "booking_id") val bookingId: kotlin.String,

    @SerialName(value = "service_id") val serviceId: kotlin.String,

    @SerialName(value = "service_name") val serviceName: kotlin.String,

    @SerialName(value = "price") val price: kotlin.Double,

    @SerialName(value = "duration_minutes") val durationMinutes: kotlin.Int,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "currency") val currency: kotlin.String? = "ILS"

)   {

}

