/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param startTime 
 * @param endTime 
 * @param providerId 
 * @param isAvailable Доступность слота
 */
@Serializable

data class BookingAvailableSlotResponse (

    @SerialName(value = "start_time") val startTime: kotlinx.datetime.Instant,

    @SerialName(value = "end_time") val endTime: kotlinx.datetime.Instant,

    @SerialName(value = "provider_id") val providerId: kotlin.String,

    /* Доступность слота */
    @SerialName(value = "is_available") val isAvailable: kotlin.Boolean? = true

)   {

}

