/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param providerId Provider ID (providers.id from catalog)
 * @param startTime Время начала
 * @param serviceIds Список услуг
 * @param notes 
 */
@Serializable

data class BookingCreate (

    /* Provider ID (providers.id from catalog) */
    @SerialName(value = "provider_id") val providerId: kotlin.String,

    /* Время начала */
    @SerialName(value = "start_time") val startTime: kotlinx.datetime.Instant,

    /* Список услуг */
    @SerialName(value = "service_ids") val serviceIds: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "notes") val notes: kotlin.String? = null

)   {

}

