/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param providerId 
 * @param clientId 
 * @param status 
 * @param startTime 
 * @param endTime 
 * @param notes 
 * @param totalPrice 
 * @param totalDurationMinutes 
 * @param rescheduleCount 
 * @param confirmedAt 
 * @param confirmedBy 
 * @param cancelledAt 
 * @param cancelledBy 
 * @param cancellationReason 
 * @param expiredAt 
 * @param noShowMarkedAt 
 * @param noShowMarkedBy 
 * @param createdAt 
 * @param updatedAt 
 * @param providerName 
 * @param currency 
 * @param items 
 */
@Serializable

data class BookingResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "provider_id") val providerId: kotlin.String,

    @SerialName(value = "client_id") val clientId: kotlin.String,

    @SerialName(value = "status") val status: kotlin.String,

    @SerialName(value = "start_time") val startTime: kotlinx.datetime.Instant,

    @SerialName(value = "end_time") val endTime: kotlinx.datetime.Instant,

    @SerialName(value = "notes") val notes: kotlin.String?,

    @SerialName(value = "total_price") val totalPrice: kotlin.Double?,

    @SerialName(value = "total_duration_minutes") val totalDurationMinutes: kotlin.Int,

    @SerialName(value = "reschedule_count") val rescheduleCount: kotlin.Int,

    @SerialName(value = "confirmed_at") val confirmedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "confirmed_by") val confirmedBy: kotlin.String?,

    @SerialName(value = "cancelled_at") val cancelledAt: kotlinx.datetime.Instant?,

    @SerialName(value = "cancelled_by") val cancelledBy: kotlin.String?,

    @SerialName(value = "cancellation_reason") val cancellationReason: kotlin.String?,

    @SerialName(value = "expired_at") val expiredAt: kotlinx.datetime.Instant?,

    @SerialName(value = "no_show_marked_at") val noShowMarkedAt: kotlinx.datetime.Instant?,

    @SerialName(value = "no_show_marked_by") val noShowMarkedBy: kotlin.String?,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "provider_name") val providerName: kotlin.String? = "",

    @SerialName(value = "currency") val currency: kotlin.String? = "ILS",

    @SerialName(value = "items") val items: kotlin.collections.List<BookingItemResponse>? = null

)   {

}

