/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param title 
 * @param basePrice 
 * @param durationMinutes 
 * @param isCombinable 
 */
@Serializable

data class CartServiceResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "title") val title: kotlin.String,

    @SerialName(value = "base_price") val basePrice: kotlin.Int?,

    @SerialName(value = "duration_minutes") val durationMinutes: kotlin.Int,

    @SerialName(value = "is_combinable") val isCombinable: kotlin.Boolean

)   {

}

