/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param isValid 
 * @param isCombinable 
 * @param services 
 * @param totals 
 * @param warnings 
 */
@Serializable

data class CartValidateResponse (

    @SerialName(value = "is_valid") val isValid: kotlin.Boolean,

    @SerialName(value = "is_combinable") val isCombinable: kotlin.Boolean,

    @SerialName(value = "services") val services: kotlin.collections.List<CartServiceResponse>,

    @SerialName(value = "totals") val totals: CartTotalsResponse,

    @SerialName(value = "warnings") val warnings: kotlin.collections.List<CartWarningResponse>

)   {

}

