/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param type 
 * @param serviceId 
 * @param serviceTitle 
 * @param message 
 */
@Serializable

data class CartWarningResponse (

    @SerialName(value = "type") val type: kotlin.String,

    @SerialName(value = "service_id") val serviceId: kotlin.String,

    @SerialName(value = "service_title") val serviceTitle: kotlin.String,

    @SerialName(value = "message") val message: kotlin.String

)   {

}

