/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param totalDurationMinutes 
 * @param totalPrice 
 * @param servicesCount 
 */
@Serializable

data class CartTotalsResponse (

    @SerialName(value = "total_duration_minutes") val totalDurationMinutes: kotlin.Int,

    @SerialName(value = "total_price") val totalPrice: kotlin.Int,

    @SerialName(value = "services_count") val servicesCount: kotlin.Int

)   {

}

