/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param createdAt 
 * @param updatedAt 
 * @param parentId 
 * @param iconUrl 
 * @param sortOrder 
 * @param isActive 
 */
@Serializable

data class CategoryResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "name") val name: I18nStringSchema,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "parent_id") val parentId: kotlin.String? = null,

    @SerialName(value = "icon_url") val iconUrl: kotlin.String? = null,

    @SerialName(value = "sort_order") val sortOrder: kotlin.Int? = 0,

    @SerialName(value = "is_active") val isActive: kotlin.Boolean? = true

)   {

}

