/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Context switch response schema with new access token.  Note: refresh_token is set via HTTP-only cookie, not returned in body.
 *
 * @param message 
 * @param accessToken 
 */
@Serializable

data class ContextSwitchResponse (

    @SerialName(value = "message") val message: kotlin.String,

    @SerialName(value = "access_token") val accessToken: kotlin.String

)   {

}

