/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * RFC 7807 Problem Details error response.
 *
 * @param type 
 * @param title 
 * @param status 
 * @param detail 
 * @param instance 
 */
@Serializable

data class ErrorResponse (

    @SerialName(value = "type") val type: kotlin.String,

    @SerialName(value = "title") val title: kotlin.String,

    @SerialName(value = "status") val status: kotlin.Int,

    @SerialName(value = "detail") val detail: kotlin.String,

    @SerialName(value = "instance") val instance: kotlin.String

)   {

}

