/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param providerId 
 * @param provider 
 * @param createdAt 
 */
@Serializable

data class FavoriteResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "user_id") val userId: kotlin.String,

    @SerialName(value = "provider_id") val providerId: kotlin.String,

    @SerialName(value = "provider") val provider: ProviderResponse,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant

)   {

}

