/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Response for checking if provider is in favorites.
 *
 * @param isFavorite 
 * @param favoriteId 
 */
@Serializable

data class FavoriteCheckResponse (

    @SerialName(value = "is_favorite") val isFavorite: kotlin.Boolean,

    @SerialName(value = "favorite_id") val favoriteId: kotlin.String? = null

)   {

}

