/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Request schema for Firebase account linking.
 *
 * @param firebaseToken Firebase ID token
 * @param password User password
 */
@Serializable

data class FirebaseLinkRequest (

    /* Firebase ID token */
    @SerialName(value = "firebase_token") val firebaseToken: kotlin.String,

    /* User password */
    @SerialName(value = "password") val password: kotlin.String

)   {

}

