/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * DTO for Firebase account response.
 *
 * @param provider 
 * @param email 
 * @param linkedAt 
 */
@Serializable

data class FirebaseAccountDTO (

    @SerialName(value = "provider") val provider: kotlin.String,

    @SerialName(value = "email") val email: kotlin.String?,

    @SerialName(value = "linked_at") val linkedAt: kotlinx.datetime.Instant

)   {

}

