/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Request schema for Firebase account unlinking.
 *
 * @param provider Provider to unlink
 */
@Serializable

data class FirebaseUnlinkRequest (

    /* Provider to unlink */
    @SerialName(value = "provider") val provider: FirebaseUnlinkRequest.Provider

)   {

    /**
     * Provider to unlink
     *
     * Values: googlePeriodCom,applePeriodCom,phone
     */
    @Serializable
    enum class Provider(val value: kotlin.String) {
        @SerialName(value = "google.com") googlePeriodCom("google.com"),
        @SerialName(value = "apple.com") applePeriodCom("apple.com"),
        @SerialName(value = "phone") phone("phone");
    }

}

