/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param ru 
 * @param he 
 * @param en 
 */
@Serializable

data class I18nStringSchema (

    @SerialName(value = "ru") val ru: kotlin.String,

    @SerialName(value = "he") val he: kotlin.String,

    @SerialName(value = "en") val en: kotlin.String

)   {

}

