/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Profile response schema.
 *
 * @param id 
 * @param userId 
 * @param createdAt 
 * @param updatedAt 
 * @param fullName 
 * @param phone 
 * @param avatarUrl 
 * @param noShowCount Number of no-show marks
 * @param noShowRate No-show rate (0.0-1.0)
 */
@Serializable

data class ProfileResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "user_id") val userId: kotlin.String,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "full_name") val fullName: kotlin.String? = null,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "avatar_url") val avatarUrl: kotlin.String? = null,

    /* Number of no-show marks */
    @SerialName(value = "no_show_count") val noShowCount: kotlin.Int? = 0,

    /* No-show rate (0.0-1.0) */
    @SerialName(value = "no_show_rate") val noShowRate: kotlin.Double? = (0.0).toDouble()

)   {

}

