/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Profile update schema.
 *
 * @param fullName 
 * @param phone 
 * @param avatarUrl 
 */
@Serializable

data class ProfileUpdate (

    @SerialName(value = "full_name") val fullName: kotlin.String? = null,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "avatar_url") val avatarUrl: kotlin.String? = null

)   {

}

