/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param providers 
 * @param total 
 * @param limit 
 * @param offset 
 */
@Serializable

data class ProviderListResponse (

    @SerialName(value = "providers") val providers: kotlin.collections.List<ProviderResponse>,

    @SerialName(value = "total") val total: kotlin.Int,

    @SerialName(value = "limit") val limit: kotlin.Int,

    @SerialName(value = "offset") val offset: kotlin.Int

)   {

}

