/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param lat Latitude
 * @param lon Longitude
 * @param radiusKm Search radius in km
 * @param categoryId 
 * @param serviceId 
 * @param priceMin 
 * @param priceMax 
 * @param sortBy 
 * @param limit 
 * @param offset 
 */
@Serializable

data class ProviderSearchRequest (

    /* Latitude */
    @SerialName(value = "lat") val lat: kotlin.Double,

    /* Longitude */
    @SerialName(value = "lon") val lon: kotlin.Double,

    /* Search radius in km */
    @SerialName(value = "radius_km") val radiusKm: kotlin.Double? = (10.0).toDouble(),

    @SerialName(value = "category_id") val categoryId: kotlin.String? = null,

    @SerialName(value = "service_id") val serviceId: kotlin.String? = null,

    @SerialName(value = "price_min") val priceMin: kotlin.Int? = null,

    @SerialName(value = "price_max") val priceMax: kotlin.Int? = null,

    @SerialName(value = "sort_by") val sortBy: kotlin.String? = "distance",

    @SerialName(value = "limit") val limit: kotlin.Int? = 20,

    @SerialName(value = "offset") val offset: kotlin.Int? = 0

)   {

}

