/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Composite response for provider detail page.  Combines provider info + services + favorite status in a single request, replacing 3 separate API calls from the mobile client.
 *
 * @param provider 
 * @param services 
 * @param isFavorite 
 */
@Serializable

data class ProviderDetailResponse (

    @SerialName(value = "provider") val provider: ProviderResponse,

    @SerialName(value = "services") val services: kotlin.collections.List<PublicProviderServiceItemResponse>,

    @SerialName(value = "is_favorite") val isFavorite: kotlin.Boolean? = null

)   {

}

