/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param providerId 
 * @param serviceId 
 * @param createdAt 
 * @param updatedAt 
 * @param customPrice 
 * @param isActive 
 * @param service 
 */
@Serializable

data class ProviderServiceResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "provider_id") val providerId: kotlin.String,

    @SerialName(value = "service_id") val serviceId: kotlin.String,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "custom_price") val customPrice: kotlin.Int? = null,

    @SerialName(value = "is_active") val isActive: kotlin.Boolean? = true,

    @SerialName(value = "service") val service: ServiceResponse? = null

)   {

}

