/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param userId 
 * @param displayName 
 * @param ratingCached 
 * @param reviewsCount 
 * @param createdAt 
 * @param updatedAt 
 * @param bio 
 * @param avatarUrl 
 * @param phone 
 * @param location 
 * @param address 
 * @param isVerified 
 * @param isActive 
 * @param distanceKm 
 * @param autoAcceptBookings Auto-accept all bookings
 * @param allowRescheduling Allow clients to reschedule
 * @param minBookingNoticeHours Minimum hours before booking
 */
@Serializable

data class ProviderResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "user_id") val userId: kotlin.String,

    @SerialName(value = "display_name") val displayName: kotlin.String,

    @SerialName(value = "rating_cached") val ratingCached: kotlin.Double,

    @SerialName(value = "reviews_count") val reviewsCount: kotlin.Int,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "bio") val bio: kotlin.String? = null,

    @SerialName(value = "avatar_url") val avatarUrl: kotlin.String? = null,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "location") val location: LocationSchema? = null,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "is_verified") val isVerified: kotlin.Boolean? = false,

    @SerialName(value = "is_active") val isActive: kotlin.Boolean? = true,

    @SerialName(value = "distance_km") val distanceKm: kotlin.Double? = null,

    /* Auto-accept all bookings */
    @SerialName(value = "auto_accept_bookings") val autoAcceptBookings: kotlin.Boolean? = false,

    /* Allow clients to reschedule */
    @SerialName(value = "allow_rescheduling") val allowRescheduling: kotlin.Boolean? = true,

    /* Minimum hours before booking */
    @SerialName(value = "min_booking_notice_hours") val minBookingNoticeHours: kotlin.Int? = 2

)   {

}

