/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param providerId 
 * @param displayName 
 * @param avatarUrl 
 * @param rating 
 * @param reviewsCount 
 * @param availableSlot 
 * @param totalPrice 
 */
@Serializable

data class ProviderWithSlotResponse (

    @SerialName(value = "provider_id") val providerId: kotlin.String,

    @SerialName(value = "display_name") val displayName: kotlin.String,

    @SerialName(value = "avatar_url") val avatarUrl: kotlin.String?,

    @SerialName(value = "rating") val rating: kotlin.Double,

    @SerialName(value = "reviews_count") val reviewsCount: kotlin.Int,

    @SerialName(value = "available_slot") val availableSlot: CatalogAvailableSlotResponse,

    @SerialName(value = "total_price") val totalPrice: kotlin.Int

)   {

}

