/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Request body for provider onboarding.
 *
 * @param displayName Provider display name
 * @param bio 
 * @param phone 
 * @param address 
 * @param latitude 
 * @param longitude 
 */
@Serializable

data class ProviderOnboardingRequest (

    /* Provider display name */
    @SerialName(value = "display_name") val displayName: kotlin.String,

    @SerialName(value = "bio") val bio: kotlin.String? = null,

    @SerialName(value = "phone") val phone: kotlin.String? = null,

    @SerialName(value = "address") val address: kotlin.String? = null,

    @SerialName(value = "latitude") val latitude: kotlin.Double? = null,

    @SerialName(value = "longitude") val longitude: kotlin.Double? = null

)   {

}

