/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param serviceId 
 * @param customPrice 
 * @param isActive 
 */
@Serializable

data class ProviderServiceCreateRequest (

    @SerialName(value = "service_id") val serviceId: kotlin.String,

    @SerialName(value = "custom_price") val customPrice: kotlin.Int? = null,

    @SerialName(value = "is_active") val isActive: kotlin.Boolean? = true

)   {

}

