/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Schema for provider reviews with rating stats.
 *
 * @param reviews 
 * @param averageRating 
 * @param totalCount 
 * @param limit 
 * @param offset 
 */
@Serializable

data class ProviderReviewsResponse (

    @SerialName(value = "reviews") val reviews: kotlin.collections.List<ReviewResponse>,

    @SerialName(value = "average_rating") val averageRating: kotlin.Double,

    @SerialName(value = "total_count") val totalCount: kotlin.Int,

    @SerialName(value = "limit") val limit: kotlin.Int,

    @SerialName(value = "offset") val offset: kotlin.Int

)   {

}

