/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Public response schema for a single provider service - mobile-aligned.
 *
 * @param id 
 * @param categoryId 
 * @param categoryName 
 * @param title 
 * @param basePrice 
 * @param durationMinutes 
 * @param isActive 
 * @param createdAt 
 * @param providerId 
 * @param description 
 */
@Serializable

data class PublicProviderServiceItemResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "category_id") val categoryId: kotlin.String,

    @SerialName(value = "category_name") val categoryName: I18nStringSchema,

    @SerialName(value = "title") val title: I18nStringSchema,

    @SerialName(value = "base_price") val basePrice: kotlin.Int,

    @SerialName(value = "duration_minutes") val durationMinutes: kotlin.Int,

    @SerialName(value = "is_active") val isActive: kotlin.Boolean,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "providerId") val providerId: kotlin.String? = null,

    @SerialName(value = "description") val description: I18nStringSchema? = null

)   {

}

