/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param accessToken 
 * @param refreshToken 
 * @param user 
 * @param email 
 * @param firebaseUid 
 * @param provider 
 * @param responseType 
 * @param message 
 */
@Serializable

data class ResponsePostFirebaseVerify (

    @SerialName(value = "access_token") val accessToken: kotlin.String,

    @SerialName(value = "refresh_token") val refreshToken: kotlin.String,

    @SerialName(value = "user") val user: UserResponse,

    @SerialName(value = "email") val email: kotlin.String,

    @SerialName(value = "firebase_uid") val firebaseUid: kotlin.String,

    @SerialName(value = "provider") val provider: kotlin.String,

    @SerialName(value = "response_type") val responseType: ResponsePostFirebaseVerify.ResponseType? = ResponseType.link_required,

    @SerialName(value = "message") val message: kotlin.String? = "Password verification required to link Firebase account"

)   {

    /**
     * 
     *
     * Values: link_required
     */
    @Serializable
    enum class ResponseType(val value: kotlin.String) {
        @SerialName(value = "link_required") link_required("link_required");
    }

}

