/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Schema for creating a review.
 *
 * @param bookingId 
 * @param rating Rating from 1 to 5
 * @param comment 
 * @param serviceIds 
 */
@Serializable

data class ReviewCreate (

    @SerialName(value = "booking_id") val bookingId: kotlin.String,

    /* Rating from 1 to 5 */
    @SerialName(value = "rating") val rating: kotlin.Int,

    @SerialName(value = "comment") val comment: kotlin.String? = null,

    @SerialName(value = "service_ids") val serviceIds: kotlin.collections.List<kotlin.String>? = null

)   {

}

