/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Schema for review response.
 *
 * @param id 
 * @param bookingId 
 * @param clientId 
 * @param providerId 
 * @param rating 
 * @param comment 
 * @param status 
 * @param isVerified 
 * @param serviceIds 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class ReviewResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "booking_id") val bookingId: kotlin.String,

    @SerialName(value = "client_id") val clientId: kotlin.String,

    @SerialName(value = "provider_id") val providerId: kotlin.String,

    @SerialName(value = "rating") val rating: kotlin.Int,

    @SerialName(value = "comment") val comment: kotlin.String?,

    @SerialName(value = "status") val status: kotlin.String,

    @SerialName(value = "is_verified") val isVerified: kotlin.Boolean,

    @SerialName(value = "service_ids") val serviceIds: kotlin.collections.List<kotlin.String>?,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant

)   {

}

