/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Role response schema.
 *
 * @param id 
 * @param name 
 * @param description 
 */
@Serializable

data class RoleResponse (

    @SerialName(value = "id") val id: kotlin.Int,

    @SerialName(value = "name") val name: kotlin.String,

    @SerialName(value = "description") val description: kotlin.String? = null

)   {

}

