/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param providerId 
 * @param weekday 
 * @param specificDate 
 * @param startTime 
 * @param endTime 
 * @param isWorkingDay 
 * @param slotDurationMinutes 
 * @param breakDurationMinutes 
 * @param validFrom 
 * @param validTo 
 * @param createdAt 
 * @param updatedAt 
 */
@Serializable

data class ScheduleRuleResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "provider_id") val providerId: kotlin.String,

    @SerialName(value = "weekday") val weekday: kotlin.Int?,

    @SerialName(value = "specific_date") val specificDate: kotlinx.datetime.LocalDate?,

    @SerialName(value = "start_time") val startTime: kotlinx.datetime.LocalTime,

    @SerialName(value = "end_time") val endTime: kotlinx.datetime.LocalTime,

    @SerialName(value = "is_working_day") val isWorkingDay: kotlin.Boolean,

    @SerialName(value = "slot_duration_minutes") val slotDurationMinutes: kotlin.Int,

    @SerialName(value = "break_duration_minutes") val breakDurationMinutes: kotlin.Int,

    @SerialName(value = "valid_from") val validFrom: kotlinx.datetime.LocalDate?,

    @SerialName(value = "valid_to") val validTo: kotlinx.datetime.LocalDate?,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant

)   {

}

