/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param providerId ID мастера
 * @param startTime Время начала
 * @param endTime Время окончания
 * @param weekday 
 * @param specificDate 
 * @param isWorkingDay Рабочий день или выходной
 * @param slotDurationMinutes Длительность слота в минутах
 * @param breakDurationMinutes Длительность перерыва в минутах
 * @param validFrom 
 * @param validTo 
 */
@Serializable

data class ScheduleRuleCreate (

    /* ID мастера */
    @SerialName(value = "provider_id") val providerId: kotlin.String,

    /* Время начала */
    @SerialName(value = "start_time") val startTime: kotlinx.datetime.LocalTime,

    /* Время окончания */
    @SerialName(value = "end_time") val endTime: kotlinx.datetime.LocalTime,

    @SerialName(value = "weekday") val weekday: kotlin.Int? = null,

    @SerialName(value = "specific_date") val specificDate: kotlinx.datetime.LocalDate? = null,

    /* Рабочий день или выходной */
    @SerialName(value = "is_working_day") val isWorkingDay: kotlin.Boolean? = true,

    /* Длительность слота в минутах */
    @SerialName(value = "slot_duration_minutes") val slotDurationMinutes: kotlin.Int? = 30,

    /* Длительность перерыва в минутах */
    @SerialName(value = "break_duration_minutes") val breakDurationMinutes: kotlin.Int? = 0,

    @SerialName(value = "valid_from") val validFrom: kotlinx.datetime.LocalDate? = null,

    @SerialName(value = "valid_to") val validTo: kotlinx.datetime.LocalDate? = null

)   {

}

