/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param categoryId 
 * @param title 
 * @param durationMinutes 
 * @param createdAt 
 * @param updatedAt 
 * @param description 
 * @param basePrice 
 * @param priceMin 
 * @param priceMax 
 * @param currency 
 * @param isCombinable 
 * @param isPriceVariable 
 * @param isActive 
 */
@Serializable

data class ServiceResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "category_id") val categoryId: kotlin.String,

    @SerialName(value = "title") val title: I18nStringSchema,

    @SerialName(value = "duration_minutes") val durationMinutes: kotlin.Int,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "updated_at") val updatedAt: kotlinx.datetime.Instant,

    @SerialName(value = "description") val description: I18nStringSchema? = null,

    @SerialName(value = "base_price") val basePrice: kotlin.Int? = null,

    @SerialName(value = "price_min") val priceMin: kotlin.Int? = null,

    @SerialName(value = "price_max") val priceMax: kotlin.Int? = null,

    @SerialName(value = "currency") val currency: kotlin.String? = "ILS",

    @SerialName(value = "is_combinable") val isCombinable: kotlin.Boolean? = true,

    @SerialName(value = "is_price_variable") val isPriceVariable: kotlin.Boolean? = false,

    @SerialName(value = "is_active") val isActive: kotlin.Boolean? = true

)   {

}

