/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * Set current context role request schema.
 *
 * @param role 
 */
@Serializable

data class SetContextRequest (

    @SerialName(value = "role") val role: SetContextRequest.Role

)   {

    /**
     * 
     *
     * Values: client,provider
     */
    @Serializable
    enum class Role(val value: kotlin.String) {
        @SerialName(value = "client") client("client"),
        @SerialName(value = "provider") provider("provider");
    }

}

