/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * User roles response schema.
 *
 * @param userId 
 * @param roles 
 * @param currentRole 
 */
@Serializable

data class UserRolesResponse (

    @SerialName(value = "user_id") val userId: kotlin.String,

    @SerialName(value = "roles") val roles: kotlin.collections.List<RoleResponse>,

    @SerialName(value = "current_role") val currentRole: RoleResponse? = null

)   {

}

