/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * User response schema.
 *
 * @param id 
 * @param email 
 * @param isActive 
 * @param isVerified 
 * @param roles 
 * @param createdAt 
 * @param currentRole 
 */
@Serializable

data class UserResponse (

    @SerialName(value = "id") val id: kotlin.String,

    @SerialName(value = "email") val email: kotlin.String,

    @SerialName(value = "is_active") val isActive: kotlin.Boolean,

    @SerialName(value = "is_verified") val isVerified: kotlin.Boolean,

    @SerialName(value = "roles") val roles: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "created_at") val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "current_role") val currentRole: kotlin.String? = null

)   {

}

