/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.aggregateservice.core.api.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param loc 
 * @param msg 
 * @param type 
 * @param input 
 * @param ctx 
 */
@Serializable

data class ValidationError (

    @SerialName(value = "loc") val loc: kotlin.collections.List<LocationInner>,

    @SerialName(value = "msg") val msg: kotlin.String,

    @SerialName(value = "type") val type: kotlin.String,

    @SerialName(value = "input") @Contextual val input: kotlin.Any? = null,

    @SerialName(value = "ctx") val ctx: kotlin.String? = null

)   {

}

